jobs:

# Shell script infrastructure deployment to AWS
  - name: tfDeploy
    type: runSh
    steps:
      - IN: repo-tfScripts
      - IN: params-tfScripts
      - IN: integration-aws
      - IN: trigger-tf-deploy
      - TASK:
        - script: echo "provisioning infrastructure on AWS via Terraform"
        - script: . /build/IN/repo-tfScripts/gitRepo/runTerraform.sh repo-tfScripts params-tfScripts integration-aws
      - on_success:
        - . /saveState.sh
      - on_failure:
        - . /saveState.sh
