jobs:

# Shell script infrastructure deployment to AWS
  - name: tfDeploy
    type: runSh
    steps:
      - IN: integration-aws
      - IN: repo-tfScripts
      - IN: params-tfScripts
      - IN: trigger-tf-deploy
      - TASK:
        - script: . /build/IN/repo-tfScripts/gitRepo/runTerraform.sh
